version: '3'
services:
  app: 
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data
  test-db:
    container_name: test-db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d/
volumes:
  database_volume: