/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeliveryZoneDto {
  id: number;
  title: string;
  /**
   * Полигон зоны доставки в формате GeoJSON
   */
  polygon: {
    type: "Polygon";
    /**
     * Массив колец полигона. Первое кольцо в массиве - внешнее кольцо. Остальные кольца - внутренние кольца
     *
     * @minItems 1
     * @maxItems 3
     */
    coordinates:
      | [[[number, number], [number, number], [number, number], ...[number, number][]]]
      | [
          [[number, number], [number, number], [number, number], ...[number, number][]],
          [[number, number], [number, number], [number, number], ...[number, number][]]
        ]
      | [
          [[number, number], [number, number], [number, number], ...[number, number][]],
          [[number, number], [number, number], [number, number], ...[number, number][]],
          [[number, number], [number, number], [number, number], ...[number, number][]]
        ];
  };
}
